#!/usr/bin/env python3
"""
Generator script for creating Gradient Descent Backtracking experimental setups
Creates comprehensive setups with various c1 and rho parameters
"""
import os
from pathlib import Path

def create_backtracking_setup(setup_num, c1, rho, alpha0=1.0):
    """Create gradient descent backtracking setup"""
    # Format numbers for filename
    if c1 == 1e-3:
        c1_str = "001"
    elif c1 == 1e-2:
        c1_str = "01"
    elif c1 == 1e-1:
        c1_str = "1"
    elif c1 == 0.5:
        c1_str = "05"
    else:
        c1_str = str(c1).replace('.', '')
    
    rho_str = str(rho).replace('.', '')

    content = f'''#!/usr/bin/env python3
"""
Auto-generated experimental setup #{setup_num}
Algorithm: Gradient Descent with Backtracking Line Search
Configuration: Backtracking GD - OLS Loss, c1={c1}, alpha0={alpha0}, rho={rho}
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
# Add the src directory to path
src_path = os.path.join(os.path.dirname(__file__), '..', '..')
if src_path not in sys.path:
    sys.path.insert(0, src_path)
from optimization.algorithms.gradient_descent import GradientDescentOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Get experiment name from current file name"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\\n============================================================")
    print(f"EXPERIMENTAL SETUP #{setup_num}")
    print(f"Algorithm: Gradient Descent with Backtracking Line Search")
    print(f"Configuration: Backtracking GD - OLS Loss, c1={c1}, alpha0={alpha0}, rho={rho}")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Create model with backtracking line search configuration
    model = GradientDescentOptimizer(
        ham_loss='ols',
        learning_rate={alpha0},  # Initial step size (alpha0)
        line_search_method='backtracking',
        backtrack_c1={c1},  # Armijo constant (c)
        backtrack_rho={rho}   # Reduction factor (rho)
    )

    # Training pipeline
    results = model.fit(X_train, y_train)
    metrics = model.evaluate(X_test, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test, y_test, ten_file)

    print(f"\\nSetup #{setup_num} completed successfully!")
    print(f"Configuration: Backtracking GD - c1={c1}, alpha0={alpha0}, rho={rho}")
    print(f"Final Loss: {{results.get('final_loss', 'N/A'):.6f}}")
    print(f"Test MSE: {{metrics.get('mse', 'N/A'):.6f}}")
    print(f"Results saved to: {{results_dir}}")

    return model, results, metrics

if __name__ == "__main__":
    main()'''

    filename = f"{setup_num}_gd_backtracking_ols_c1_{c1_str}_rho_{rho_str}.py"
    return filename, content

def main():
    base_dir = Path(r"C:\\Users\\Admin\\OneDrive\\Coding\\Python\\master\\optimization-for-ml\\src\\experimental_setups\\gradient_descent")
    base_dir.mkdir(parents=True, exist_ok=True)

    setups_created = []

    # Setup 145: Bổ sung rho=0.9 cho c1=1e-3
    print("Creating setup 145...")
    filename, content = create_backtracking_setup(145, 1e-3, 0.9)
    filepath = base_dir / filename
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    setups_created.append(filename)
    print(f"Created: {filename}")

    # Setup 146-150: c1=1e-2 với các rho
    print("\\nCreating setups 146-150 (c1=1e-2)...")
    setup_num = 146
    rho_values = [0.5, 0.6, 0.7, 0.8, 0.9]
    for rho in rho_values:
        filename, content = create_backtracking_setup(setup_num, 1e-2, rho)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        setups_created.append(filename)
        print(f"Created: {filename}")
        setup_num += 1

    # Setup 151-155: c1=1e-1 với các rho
    print("\\nCreating setups 151-155 (c1=1e-1)...")
    setup_num = 151
    for rho in rho_values:
        filename, content = create_backtracking_setup(setup_num, 1e-1, rho)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        setups_created.append(filename)
        print(f"Created: {filename}")
        setup_num += 1

    # Setup 156-160: c1=0.5 với các rho
    print("\\nCreating setups 156-160 (c1=0.5)...")
    setup_num = 156
    for rho in rho_values:
        filename, content = create_backtracking_setup(setup_num, 0.5, rho)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        setups_created.append(filename)
        print(f"Created: {filename}")
        setup_num += 1

    print(f"\\n============================================================")
    print(f"COMPLETED! Created {len(setups_created)} setup files (145-160)")
    print(f"============================================================")
    print("Parameter matrix:")
    print("- Setup 145: c1=1e-3, rho=0.9")
    print("- Setups 146-150: c1=1e-2, rho=[0.5, 0.6, 0.7, 0.8, 0.9]")
    print("- Setups 151-155: c1=1e-1, rho=[0.5, 0.6, 0.7, 0.8, 0.9]")
    print("- Setups 156-160: c1=0.5, rho=[0.5, 0.6, 0.7, 0.8, 0.9]")
    print("All setups use alpha0=1.0 and OLS loss function")

if __name__ == "__main__":
    main()