#!/usr/bin/env python3
"""
Generator script for creating Subgradient experimental setups
Creates comprehensive setups with various step size parameters, lambda=0.1 fixed
"""
import os
from pathlib import Path

def create_constant_step_size_setup(setup_num, step_size, lambda_val=0.1):
    """Create constant step size setup"""
    step_size_str = str(step_size).replace('.', '')
    lambda_str = str(lambda_val).replace('.', '')

    content = f'''#!/usr/bin/env python3
"""
Auto-generated experimental setup #{setup_num}
Algorithm: Subgradient Method
Configuration: Subgradient constant - step_size={step_size}, lambda={lambda_val}
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
import numpy as np
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.subgradient import SubgradientOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Lấy tên experiment từ tên file hiện tại"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\\n============================================================")
    print(f"EXPERIMENTAL SETUP #{setup_num}")
    print(f"Algorithm: Subgradient Method - constant")
    print(f"Configuration: Subgradient constant - step_size={step_size}, lambda={lambda_val}")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Add bias column for subgradient methods
    X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # Create model with specific configuration
    model = SubgradientOptimizer(
        lambda_penalty={lambda_val},

        step_size_method='constant',
        step_size={step_size}
    )

    # Training pipeline
    results = model.fit(X_train_with_bias, y_train)
    metrics = model.evaluate(X_test_with_bias, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test_with_bias, y_test, ten_file)

    print(f"\\nSetup #{setup_num} completed successfully!")
    print(f"Configuration: Subgradient constant - step_size={step_size}, lambda={lambda_val}")
    print(f"Lambda penalty: {lambda_val}")
    print(f"Step size: {step_size}")
    print(f"Results saved to: {{results_dir}}")

    return model, results, metrics

if __name__ == "__main__":
    main()'''

    filename = f"{setup_num}_subgrad_constant_step_{step_size_str}_lambda_{lambda_str}.py"
    return filename, content

def create_square_summable_setup(setup_num, a, b, lambda_val=0.1):
    """Create square summable setup"""
    a_str = str(a).replace('.', '')
    b_str = str(b).replace('.', '')
    lambda_str = str(lambda_val).replace('.', '')

    content = f'''#!/usr/bin/env python3
"""
Auto-generated experimental setup #{setup_num}
Algorithm: Subgradient Method
Configuration: Subgradient square_summable - a={a}, b={b}, lambda={lambda_val}
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
import numpy as np
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.subgradient import SubgradientOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Lấy tên experiment từ tên file hiện tại"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\\n============================================================")
    print(f"EXPERIMENTAL SETUP #{setup_num}")
    print(f"Algorithm: Subgradient Method - square_summable")
    print(f"Configuration: Subgradient square_summable - a={a}, b={b}, lambda={lambda_val}")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Add bias column for subgradient methods
    X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # Create model with specific configuration
    model = SubgradientOptimizer(
        lambda_penalty={lambda_val},

        step_size_method='square_summable',
        square_summable_a={a},
        square_summable_b={b}
    )

    # Training pipeline
    results = model.fit(X_train_with_bias, y_train)
    metrics = model.evaluate(X_test_with_bias, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test_with_bias, y_test, ten_file)

    print(f"\\nSetup #{setup_num} completed successfully!")
    print(f"Configuration: Subgradient square_summable - a={a}, b={b}, lambda={lambda_val}")
    print(f"Lambda penalty: {lambda_val}")
    print(f"Square summable a: {a}, b: {b}")
    print(f"Results saved to: {{results_dir}}")

    return model, results, metrics

if __name__ == "__main__":
    main()'''

    filename = f"{setup_num}_subgrad_square_summable_a{a_str}_b{b_str}_lambda_{lambda_str}.py"
    return filename, content

def create_non_summable_setup(setup_num, a, lambda_val=0.1):
    """Create non-summable diminishing setup"""
    a_str = str(a).replace('.', '')
    lambda_str = str(lambda_val).replace('.', '')

    content = f'''#!/usr/bin/env python3
"""
Auto-generated experimental setup #{setup_num}
Algorithm: Subgradient Method
Configuration: Subgradient non_summable_diminishing - a={a}, lambda={lambda_val}
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
import numpy as np
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.subgradient import SubgradientOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Lấy tên experiment từ tên file hiện tại"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\\n============================================================")
    print(f"EXPERIMENTAL SETUP #{setup_num}")
    print(f"Algorithm: Subgradient Method - non_summable_diminishing")
    print(f"Configuration: Subgradient non_summable_diminishing - a={a}, lambda={lambda_val}")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Add bias column for subgradient methods
    X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # Create model with specific configuration
    model = SubgradientOptimizer(
        lambda_penalty={lambda_val},

        step_size_method='non_summable_diminishing',
        non_summable_a={a}
    )

    # Training pipeline
    results = model.fit(X_train_with_bias, y_train)
    metrics = model.evaluate(X_test_with_bias, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test_with_bias, y_test, ten_file)

    print(f"\\nSetup #{setup_num} completed successfully!")
    print(f"Configuration: Subgradient non_summable_diminishing - a={a}, lambda={lambda_val}")
    print(f"Lambda penalty: {lambda_val}")
    print(f"Non-summable a: {a}")
    print(f"Results saved to: {{results_dir}}")

    return model, results, metrics

if __name__ == "__main__":
    main()'''

    filename = f"{setup_num}_subgrad_non_summable_a{a_str}_lambda_{lambda_str}.py"
    return filename, content

def create_constant_step_length_setup(setup_num, step_length, lambda_val=0.1):
    """Create constant step length setup"""
    step_length_str = str(step_length).replace('.', '')
    lambda_str = str(lambda_val).replace('.', '')

    content = f'''#!/usr/bin/env python3
"""
Auto-generated experimental setup #{setup_num}
Algorithm: Subgradient Method
Configuration: Subgradient constant_step_length - step_length={step_length}, lambda={lambda_val}
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
import numpy as np
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.subgradient import SubgradientOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Lấy tên experiment từ tên file hiện tại"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\\n============================================================")
    print(f"EXPERIMENTAL SETUP #{setup_num}")
    print(f"Algorithm: Subgradient Method - constant_step_length")
    print(f"Configuration: Subgradient constant_step_length - step_length={step_length}, lambda={lambda_val}")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Add bias column for subgradient methods
    X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # Create model with specific configuration
    model = SubgradientOptimizer(
        lambda_penalty={lambda_val},

        step_size_method='constant_step_length',
        step_length={step_length}
    )

    # Training pipeline
    results = model.fit(X_train_with_bias, y_train)
    metrics = model.evaluate(X_test_with_bias, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test_with_bias, y_test, ten_file)

    print(f"\\nSetup #{setup_num} completed successfully!")
    print(f"Configuration: Subgradient constant_step_length - step_length={step_length}, lambda={lambda_val}")
    print(f"Lambda penalty: {lambda_val}")
    print(f"Step length: {step_length}")
    print(f"Results saved to: {{results_dir}}")

    return model, results, metrics

if __name__ == "__main__":
    main()'''

    filename = f"{setup_num}_subgrad_constant_step_length_{step_length_str}_lambda_{lambda_str}.py"
    return filename, content

def main():
    base_dir = Path(r"C:\\Users\\Admin\\OneDrive\\Coding\\Python\\master\\optimization-for-ml\\src\\experimental_setups\\subgradient")
    base_dir.mkdir(parents=True, exist_ok=True)

    setup_num = 501

    # 1. Constant Step Size (501-515)
    print("Creating Constant Step Size setups...")
    constant_step_sizes = [0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1]
    for step_size in constant_step_sizes:
        filename, content = create_constant_step_size_setup(setup_num, step_size)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Created: {filename}")
        setup_num += 1

    # 2. Square Summable (516-537)
    print("\\nCreating Square Summable setups...")
    square_summable_configs = [
        # a=0.5: b=[0, 0.5, 1, 2]
        (0.5, 0), (0.5, 0.5), (0.5, 1), (0.5, 2),
        # a=1.0: b=[0, 0.5, 1, 1.5, 2, 3, 5]
        (1.0, 0), (1.0, 0.5), (1.0, 1), (1.0, 1.5), (1.0, 2), (1.0, 3), (1.0, 5),
        # a=1.5: b=[0, 0.5, 1, 2]
        (1.5, 0), (1.5, 0.5), (1.5, 1), (1.5, 2),
        # a=2.0: b=[0, 1, 2, 3]
        (2.0, 0), (2.0, 1), (2.0, 2), (2.0, 3),
        # a=3.0: b=[0, 1, 2]
        (3.0, 0), (3.0, 1), (3.0, 2)
    ]
    for a, b in square_summable_configs:
        filename, content = create_square_summable_setup(setup_num, a, b)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Created: {filename}")
        setup_num += 1

    # 3. Non-summable Diminishing (538-552)
    print("\\nCreating Non-summable Diminishing setups...")
    non_summable_a_values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.5, 2.0, 3.0, 5.0]
    for a in non_summable_a_values:
        filename, content = create_non_summable_setup(setup_num, a)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Created: {filename}")
        setup_num += 1

    # 4. Constant Step Length (553-567)
    print("\\nCreating Constant Step Length setups...")
    step_lengths = [0.02, 0.03, 0.05, 0.07, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5, 0.7, 1.0]
    for step_length in step_lengths:
        filename, content = create_constant_step_length_setup(setup_num, step_length)
        filepath = base_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Created: {filename}")
        setup_num += 1

    print(f"\\nCompleted! Created {setup_num - 501} setup files (501-{setup_num-1})")
    print("All setups use lambda_penalty=0.1")

if __name__ == "__main__":
    main()