#!/usr/bin/env python3
"""
Auto-generated experimental setup #607
Algorithm: BFGS (Quasi-Newton) + L2 Regularization
Configuration: BFGS - Ridge Loss, c1=1e-1, rho=0.4, c2=None, lambda=0.001
Generated by: regularization evaluation script
"""
import sys
import os
from pathlib import Path
# Add the src directory to path
src_path = os.path.join(os.path.dirname(__file__), '..', '..')
if src_path not in sys.path:
    sys.path.insert(0, src_path)
from optimization.algorithms.quasi_newton import QuasiNewtonOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Get experiment name from current file name"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\n============================================================")
    print(f"EXPERIMENTAL SETUP #607")
    print(f"Algorithm: BFGS (Quasi-Newton) + L2 Regularization")
    print(f"Configuration: BFGS - Ridge Loss, c1=1e-1, rho=0.4, c2=None, lambda=0.001")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Create model with specific configuration + Ridge regularization
    model = QuasiNewtonOptimizer(
        loss_type='ridge',
        method='bfgs',
        line_search_method='backtracking',
        backtrack_c1=1e-1,
        backtrack_rho=0.4,
        backtrack_c2=None,
        convergence_tolerance=1e-3,
        max_iterations=50000,
        regularization=0.001  # L2 regularization parameter
    )

    # Training pipeline
    results = model.fit(X_train, y_train)
    metrics = model.evaluate(X_test, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test, y_test, ten_file)

    print(f"\nSetup #607 completed successfully!")
    print(f"Configuration: BFGS + Ridge - c1=1e-1, rho=0.4, c2=None, lambda=0.001")
    print(f"Final Loss: {results.get('final_loss', 'N/A'):.6f}")
    print(f"Test MSE: {metrics.get('mse', 'N/A'):.6f}")
    print(f"Results saved to: {results_dir}")

    return model, results, metrics

if __name__ == "__main__":
    main()