#!/usr/bin/env python3
"""
Auto-generated experimental setup #615
Algorithm: Subgradient Method + LASSO Regularization
Configuration: Subgradient constant - step_size=0.07, lambda=2.0
Generated by: regularization evaluation script (based on best LASSO setup 502)
"""
import sys
import os
from pathlib import Path
import numpy as np
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.subgradient import SubgradientOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Lấy tên experiment từ tên file hiện tại"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\n============================================================")
    print(f"EXPERIMENTAL SETUP #615")
    print(f"Algorithm: Subgradient Method + LASSO Regularization")
    print(f"Configuration: Subgradient constant - step_size=0.07, lambda=2.0")
    print(f"============================================================")

    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()

    # Add bias column for subgradient methods
    X_train_with_bias = np.hstack([np.ones((X_train.shape[0], 1)), X_train])
    X_test_with_bias = np.hstack([np.ones((X_test.shape[0], 1)), X_test])

    # Create model with specific configuration
    model = SubgradientOptimizer(
        lambda_penalty=2.0,
        step_size_method='constant',
        step_size=0.07
    )

    # Training pipeline
    results = model.fit(X_train_with_bias, y_train)
    metrics = model.evaluate(X_test_with_bias, y_test)

    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)

    # Create visualizations
    model.plot_results(X_test_with_bias, y_test, ten_file)

    print(f"\nSetup #615 completed successfully!")
    print(f"Configuration: Subgradient + LASSO - step_size=0.07, lambda=2.0")
    print(f"Lambda penalty: 2.0")
    print(f"Step size: 0.07")
    print(f"Results saved to: {results_dir}")

    return model, results, metrics

if __name__ == "__main__":
    main()