#!/usr/bin/env python3
"""
Auto-generated experimental setup #140
Algorithm: Gradient Descent
Configuration: Basic GD - OLS Loss, LR=0.30
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
# Add the src directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
from optimization.algorithms.gradient_descent import GradientDescentOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Get experiment name from current file name"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\n============================================================")
    print(f"EXPERIMENTAL SETUP #140")
    print(f"Algorithm: Gradient Descent")
    print(f"Configuration: Basic GD - OLS Loss, LR=0.30")
    print(f"============================================================")
    
    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()
    
    # Create model with specific configuration
    model = GradientDescentOptimizer(
        ham_loss='ols',
        learning_rate=0.30,
        step_size_method='constant'
    )
    
    # Training pipeline
    results = model.fit(X_train, y_train)
    metrics = model.evaluate(X_test, y_test)
    
    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)
    
    # Create visualizations
    model.plot_results(X_test, y_test, ten_file)
    
    print(f"\nSetup #140 completed successfully!")
    print(f"Configuration: Basic GD - OLS Loss, LR=0.30")
    print(f"Final Loss: {results.get('final_loss', 'N/A'):.6f}")
    print(f"Test MSE: {metrics.get('mse', 'N/A'):.6f}")
    print(f"Results saved to: {results_dir}")
    
    return model, results, metrics

if __name__ == "__main__":
    main()
