#!/usr/bin/env python3
"""
Auto-generated experimental setup #151
Algorithm: Newton Method
Configuration: Pure Newton - OLS Loss, Alpha=0.6
Generated by: setup creation script
"""
import sys
import os
from pathlib import Path
# Add the src directory to path
src_path = os.path.join(os.path.dirname(__file__), '..', '..')
if src_path not in sys.path:
    sys.path.insert(0, src_path)
from optimization.algorithms.newton_method import NewtonOptimizer
from utils.data_process_utils import load_du_lieu

def get_experiment_name():
    """Get experiment name from current file name"""
    import inspect
    frame = inspect.currentframe()
    filename = frame.f_back.f_globals['__file__']
    return Path(filename).stem

def main():
    print(f"\n============================================================")
    print(f"EXPERIMENTAL SETUP #151")
    print(f"Algorithm: Newton Method")
    print(f"Configuration: Pure Newton - OLS Loss, Alpha=0.6")
    print(f"============================================================")
    
    # Load data
    X_train, X_test, y_train, y_test = load_du_lieu()
    
    # Create model with specific configuration
    model = NewtonOptimizer(
        loss_type='ols',
        damping_strategy='constant',
        damping_factor=0.6,
        line_search_method='none',
        convergence_tolerance=1e-6,
        max_iterations=50000
    )
    
    # Training pipeline
    results = model.fit(X_train, y_train)
    metrics = model.evaluate(X_test, y_test)
    
    # Save results with automatic naming
    ten_file = get_experiment_name()
    results_dir = model.save_results(ten_file)
    
    # Create visualizations
    model.plot_results(X_test, y_test, ten_file)
    
    print(f"\nSetup #151 completed successfully!")
    print(f"Configuration: Pure Newton - OLS Loss, Alpha=0.6")
    print(f"Final Loss: {results.get('final_loss', 'N/A'):.6f}")
    print(f"Test MSE: {metrics.get('mse', 'N/A'):.6f}")
    print(f"Results saved to: {results_dir}")
    
    return model, results, metrics

if __name__ == "__main__":
    main()